# Generated by Django 5.1.6 on 2025-03-16 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user.userdetail'),
            preserve_default=False,
        ),
    ]
