# Generated by Django 5.1.6 on 2025-03-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_printorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
