# Generated by Django 5.1.6 on 2025-03-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_printorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
