# Generated by Django 5.1.6 on 2025-03-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_printorder_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='payment_status',
            field=models.CharField(choices=[('COD', 'COD'), ('Paid', 'Paid')], default='COD', max_length=20),
        ),
    ]
